[Rendering]
Width=360
Height=80
RenderDriver=vulkan
HeatColorsImage=assets/heat_color_ramp8.png
;ParticleSprite=explosion_1
ParticleSpriteSheet=BigFlare
ParticleSpriteIndex=0
UseSpriteIndex=true
SpriteScale=0.01
ExtraRadius=4
HeatScale=6
InvertLayer=false
UseHeatAsLayer=true

[Spawners]
OffsetX=16
OffsetY=75
Spacing=8
Interval=0.0001
ObjectRadius=2

[Physics]
BoundsOffsetX=0
BoundsOffsetY=0
BoundsWidth=370
BoundsHeight=80
MaxObjectCount=256
_DEBUG_MaxObjectCount=800
CellSize=8
GravityX=0
GravityY=200
HeatForceX=0
HeatForceY=-400
HeatTransferRate=0.00001
HeatDecay=0.3
HeaterZoneSize=0.22
HeaterHeatDelta=0.4
CoolerZoneSize=0.3
CoolerHeatDelta=-2
SquishZoneSize=0.6
SquishZoneForceMin=0
SquishZoneForceMax=1000
; SurfaceTension=0.01
