[Rendering]
Width=360
Height=80
HeatColorsImage=assets/heat_color_ramp7.png
;ParticleSprite=explosion-01
ParticleSpriteSheet=BigFlare
ParticleSpriteIndex=0
UseSpriteIndex=true
SpriteScale=0.001
ExtraRadius=40
HeatScale=20
InvertLayer=false
UseHeatAsLayer=true

[Spawners]
OffsetX=16
OffsetY=20
Spacing=4
Interval=0.001
ObjectRadius=0.5

[Physics]
BoundsOffsetX=0
BoundsOffsetY=-80
BoundsWidth=360
BoundsHeight=160
MaxObjectCount=4000
_DEBUG_MaxObjectCount=800
CellSize=4
GravityX=0
GravityY=100
HeatForceX=0
HeatForceY=-200
HeatTransferRate=0.00001
HeatDecay=1gs

HeaterZoneSize=0.10
HeaterHeatDelta=4
CoolerZoneSize=0.1
CoolerHeatDelta=-1000
; SurfaceTension=0.01
