#include "Util.h"

BINARY_SEARCH_TOOLS_IMPL(int8);
BINARY_SEARCH_TOOLS_IMPL(int16);
BINARY_SEARCH_TOOLS_IMPL(int32);
BINARY_SEARCH_TOOLS_IMPL(int64);
BINARY_SEARCH_TOOLS_IMPL(uint8);
BINARY_SEARCH_TOOLS_IMPL(uint16);
BINARY_SEARCH_TOOLS_IMPL(uint32);
BINARY_SEARCH_TOOLS_IMPL(uint64);
BINARY_SEARCH_TOOLS_IMPL(flt32);
BINARY_SEARCH_TOOLS_IMPL(flt64);
